import { motion } from 'framer-motion';
import { FileText } from 'lucide-react';
import { PublicPageLayout } from '../../components/common';
import { Card, CardBody } from '../../components/ui';

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: `By accessing or using ArchiMind AI, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use our services. Your continued use of the platform constitutes ongoing acceptance of these terms.`,
  },
  {
    title: '2. Description of Service',
    content: `ArchiMind AI provides an AI-powered architecture design platform that generates conceptual floor plans, visualizations, and design recommendations based on user input. The service is provided on a subscription basis with different tiers offering varying levels of features and usage limits.`,
  },
  {
    title: '3. User Accounts',
    content: `You must provide accurate and complete information when creating an account. You are responsible for maintaining the security of your account credentials and for all activities that occur under your account. You must be at least 13 years old to use this service.`,
  },
  {
    title: '4. Acceptable Use',
    content: `You agree not to use ArchiMind AI to create designs for illegal purposes, infringe on intellectual property rights, upload malicious content, attempt to disrupt service operations, or use automated tools to exceed usage limits. Violations may result in account suspension or termination.`,
  },
  {
    title: '5. Intellectual Property',
    content: `All designs generated by ArchiMind AI are the property of the user who created them. However, the underlying AI models, platform code, and brand assets remain the intellectual property of ArchiMind AI. You may not reverse engineer, copy, or redistribute the platform itself.`,
  },
  {
    title: '6. Subscription and Billing',
    content: `Paid subscriptions are billed on a recurring basis (monthly or annually). You can cancel at any time, with access continuing until the end of your current billing period. We offer a 14-day money-back guarantee for first-time paid subscriptions. Prices may change with prior notice.`,
  },
  {
    title: '7. Limitation of Liability',
    content: `ArchiMind AI provides conceptual designs for informational and planning purposes only. All designs must be reviewed by licensed architects and structural engineers before construction. We are not liable for any damages resulting from the use of generated designs in actual construction projects.`,
  },
  {
    title: '8. Service Availability',
    content: `We strive for 99.9% uptime but do not guarantee uninterrupted service. We may perform maintenance, updates, or changes that temporarily affect availability. We are not liable for disruptions caused by factors beyond our control.`,
  },
  {
    title: '9. Termination',
    content: `Either party may terminate this agreement at any time. Upon termination, your data will be retained for 30 days before permanent deletion. We reserve the right to suspend or terminate accounts that violate these terms.`,
  },
  {
    title: '10. Changes to Terms',
    content: `We may update these Terms of Service periodically. Users will be notified of significant changes. Continued use after changes constitutes acceptance of the updated terms.`,
  },
  {
    title: '11. Contact',
    content: `For questions about these Terms of Service, contact us at support@archimind.ai.`,
  },
];

export function TermsOfServicePage() {
  return (
    <PublicPageLayout
      title="Terms of Service"
      subtitle="Last updated: July 10, 2026. Please read these terms carefully before using our service."
    >
      <div className="space-y-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <Card className="bg-gradient-to-r from-gold-500/10 to-transparent border-gold-500/20">
            <CardBody className="p-6 flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl bg-gold-500/20 flex items-center justify-center flex-shrink-0">
                <FileText size={24} className="text-gold-400" />
              </div>
              <div>
                <h3 className="font-semibold mb-2">Agreement Overview</h3>
                <p className="text-sm text-luxury-silver leading-relaxed">
                  These terms govern your use of ArchiMind AI. By using the platform, you agree to these terms.
                  Designs are conceptual — always consult licensed professionals before construction.
                </p>
              </div>
            </CardBody>
          </Card>
        </motion.div>

        {sections.map((section, i) => (
          <motion.div
            key={section.title}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: i * 0.05 }}
          >
            <Card>
              <CardBody className="p-6">
                <h2 className="text-lg font-display font-bold mb-3 text-gold-400">{section.title}</h2>
                <p className="text-luxury-silver leading-relaxed">{section.content}</p>
              </CardBody>
            </Card>
          </motion.div>
        ))}
      </div>
    </PublicPageLayout>
  );
}
